#pragma once

#include <array>

#include <Audio/Enums/SoundIDs.h>
#include <eSurfaceType.h>

struct CollisionLookupEntry {
    eSoundID MinSoundID, MaxSoundID; //!< Sound ID ranges for this surface (NOTE: This was `int32`, but `eSoundID` is `int16`)
    int32    MaxStartAtPercentage;   //!< Max start at (in %)
    int32    ParamD;                 //!< Some coefficient between surfaces [0-100] used in some cases to determine sound speed (and volume from it) based on velocity
};

static inline constexpr std::array<CollisionLookupEntry, TOTAL_NUM_COLLISION_SURFACE_TYPES> gCollisionLookup = {{
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [0]   = SURFACE_DEFAULT
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [1]   = SURFACE_TARMAC
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [2]   = SURFACE_TARMAC_FUCKED
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [3]   = SURFACE_TARMAC_REALLYFUCKED
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [4]   = SURFACE_PAVEMENT
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [5]   = SURFACE_PAVEMENT_FUCKED
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [6]   = SURFACE_GRAVEL
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [7]   = SURFACE_FUCKED_CONCRETE
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [8]   = SURFACE_PAINTED_GROUND
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [9]   = SURFACE_GRASS_SHORT_LUSH
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [10]  = SURFACE_GRASS_MEDIUM_LUSH
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [11]  = SURFACE_GRASS_LONG_LUSH
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [12]  = SURFACE_GRASS_SHORT_DRY
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [13]  = SURFACE_GRASS_MEDIUM_DRY
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [14]  = SURFACE_GRASS_LONG_DRY
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [15]  = SURFACE_GOLFGRASS_ROUGH
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [16]  = SURFACE_GOLFGRASS_SMOOTH
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [17]  = SURFACE_STEEP_SLIDYGRASS
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [18]  = SURFACE_STEEP_CLIFF
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [19]  = SURFACE_FLOWERBED
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [20]  = SURFACE_MEADOW
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [21]  = SURFACE_WASTEGROUND
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [22]  = SURFACE_WOODLANDGROUND
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [23]  = SURFACE_VEGETATION
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [24]  = SURFACE_MUD_WET
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [25]  = SURFACE_MUD_DRY
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [26]  = SURFACE_DIRT
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [27]  = SURFACE_DIRTTRACK
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [28]  = SURFACE_SAND_DEEP
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [29]  = SURFACE_SAND_MEDIUM
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [30]  = SURFACE_SAND_COMPACT
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [31]  = SURFACE_SAND_ARID
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [32]  = SURFACE_SAND_MORE
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [33]  = SURFACE_SAND_BEACH
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [34]  = SURFACE_CONCRETE_BEACH
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [35]  = SURFACE_ROCK_DRY
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [36]  = SURFACE_ROCK_WET
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [37]  = SURFACE_ROCK_CLIFF
    { -1,                                  -1,                                  0,  20  }, // [38]  = SURFACE_WATER_RIVERBED
    { -1,                                  -1,                                  0,  20  }, // [39]  = SURFACE_WATER_SHALLOW
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [40]  = SURFACE_CORNFIELD
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [41]  = SURFACE_HEDGE
    { SND_GENRL_COLLISIONS_CRATE1,         SND_GENRL_COLLISIONS_CRATE3,         90, 50  }, // [42]  = SURFACE_WOOD_CRATES
    { SND_GENRL_COLLISIONS_COLSOLIDWOOD,   SND_GENRL_COLLISIONS_COLSOLIDWOOD,   0,  50  }, // [43]  = SURFACE_WOOD_SOLID
    { SND_GENRL_COLLISIONS_FENCE_HEAVY,    SND_GENRL_COLLISIONS_FENCE_HEAVY,    60, 40  }, // [44]  = SURFACE_WOOD_THIN
    { -1,                                  -1,                                  0,  30  }, // [45]  = SURFACE_GLASS
    { -1,                                  -1,                                  0,  30  }, // [46]  = SURFACE_GLASS_WINDOWS_LARGE
    { -1,                                  -1,                                  0,  30  }, // [47]  = SURFACE_GLASS_WINDOWS_SMALL
    { -1,                                  -1,                                  0,  0   }, // [48]  = SURFACE_EMPTY1
    { -1,                                  -1,                                  0,  0   }, // [49]  = SURFACE_EMPTY2
    { SND_GENRL_COLLISIONS_GARAGE_DOOR,    SND_GENRL_COLLISIONS_GARAGE_DOOR,    90, 80  }, // [50]  = SURFACE_GARAGE_DOOR
    { SND_GENRL_COLLISIONS_SOLID_METAL,    SND_GENRL_COLLISIONS_SOLID_METAL,    60, 100 }, // [51]  = SURFACE_THICK_METAL_PLATE
    { SND_GENRL_COLLISIONS_SCAFFOLD_TIGHT, SND_GENRL_COLLISIONS_SCAFFOLD_TIGHT, 80, 100 }, // [52]  = SURFACE_SCAFFOLD_POLE
    { SND_GENRL_COLLISIONS_COLLAMPPOST,    SND_GENRL_COLLISIONS_COLLAMPPOST,    40, 100 }, // [53]  = SURFACE_LAMP_POST
    { SND_GENRL_COLLISIONS_WIRE_FENCE1,    SND_GENRL_COLLISIONS_WIRE_FENCE3,    80, 40  }, // [54]  = SURFACE_METAL_GATE
    { SND_GENRL_COLLISIONS_WIRE_FENCE1,    SND_GENRL_COLLISIONS_WIRE_FENCE3,    80, 40  }, // [55]  = SURFACE_METAL_CHAIN_FENCE
    { SND_GENRL_COLLISIONS_SOLID_METAL,    SND_GENRL_COLLISIONS_SOLID_METAL,    60, 100 }, // [56]  = SURFACE_GIRDER
    { SND_GENRL_COLLISIONS_HYDRANT,        SND_GENRL_COLLISIONS_HYDRANT,        50, 100 }, // [57]  = SURFACE_FIRE_HYDRANT
    { SND_GENRL_COLLISIONS_COLCONTAINER,   SND_GENRL_COLLISIONS_COLCONTAINER,   60, 100 }, // [58]  = SURFACE_CONTAINER
    { SND_GENRL_COLLISIONS_DISPENSER,      SND_GENRL_COLLISIONS_DISPENSER,      70, 60  }, // [59]  = SURFACE_NEWS_VENDOR
    { SND_GENRL_COLLISIONS_RUBBER,         SND_GENRL_COLLISIONS_RUBBER,         0,  30  }, // [60]  = SURFACE_WHEELBASE
    { SND_GENRL_COLLISIONS_CARDBOARD_BOX1, SND_GENRL_COLLISIONS_CARDBOARD_BOX3, 0,  40  }, // [61]  = SURFACE_CARDBOARDBOX
    { -1,                                  -1,                                  0,  20  }, // [62]  = SURFACE_PED
    { SND_GENRL_COLLISIONS_COLCAR01,       SND_GENRL_COLLISIONS_COLCAR12,       90, 100 }, // [63]  = SURFACE_CAR
    { SND_GENRL_COLLISIONS_COLCAR01,       SND_GENRL_COLLISIONS_COLCAR12,       90, 100 }, // [64]  = SURFACE_CAR_PANEL
    { SND_GENRL_COLLISIONS_COLCAR01,       SND_GENRL_COLLISIONS_COLCAR12,       90, 100 }, // [65]  = SURFACE_CAR_MOVINGCOMPONENT
    { -1,                                  -1,                                  1,  20  }, // [66]  = SURFACE_TRANSPARENT_CLOTH
    { SND_GENRL_COLLISIONS_RUBBER,         SND_GENRL_COLLISIONS_RUBBER,         0,  30  }, // [67]  = SURFACE_RUBBER
    { SND_GENRL_COLLISIONS_BARREL_CONE,    SND_GENRL_COLLISIONS_BARREL_CONE,    60, 30  }, // [68]  = SURFACE_PLASTIC
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [69]  = SURFACE_TRANSPARENT_STONE
    { SND_GENRL_COLLISIONS_COLBENCH1,      SND_GENRL_COLLISIONS_COLBENCH1,      80, 50  }, // [70]  = SURFACE_WOOD_BENCH
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [71]  = SURFACE_CARPET
    { SND_GENRL_COLLISIONS_COLSOLIDWOOD,   SND_GENRL_COLLISIONS_COLSOLIDWOOD,   0,  50  }, // [72]  = SURFACE_FLOORBOARD
    { SND_GENRL_COLLISIONS_COLSOLIDWOOD,   SND_GENRL_COLLISIONS_COLSOLIDWOOD,   0,  50  }, // [73]  = SURFACE_STAIRSWOOD
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [74]  = SURFACE_P_SAND
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [75]  = SURFACE_P_SAND_DENSE
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [76]  = SURFACE_P_SAND_ARID
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [77]  = SURFACE_P_SAND_COMPACT
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [78]  = SURFACE_P_SAND_ROCKY
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [79]  = SURFACE_P_SANDBEACH
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [80]  = SURFACE_P_GRASS_SHORT
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [81]  = SURFACE_P_GRASS_MEADOW
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [82]  = SURFACE_P_GRASS_DRY
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [83]  = SURFACE_P_WOODLAND
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [84]  = SURFACE_P_WOODDENSE
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [85]  = SURFACE_P_ROADSIDE
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [86]  = SURFACE_P_ROADSIDEDES
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [87]  = SURFACE_P_FLOWERBED
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [88]  = SURFACE_P_WASTEGROUND
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [89]  = SURFACE_P_CONCRETE
    { SND_GENRL_COLLISIONS_COLSOLIDWOOD,   SND_GENRL_COLLISIONS_COLSOLIDWOOD,   0,  50  }, // [90]  = SURFACE_P_OFFICEDESK
    { SND_GENRL_COLLISIONS_COLSOLIDWOOD,   SND_GENRL_COLLISIONS_COLSOLIDWOOD,   0,  50  }, // [91]  = SURFACE_P_711SHELF1
    { SND_GENRL_COLLISIONS_COLSOLIDWOOD,   SND_GENRL_COLLISIONS_COLSOLIDWOOD,   0,  50  }, // [92]  = SURFACE_P_711SHELF2
    { SND_GENRL_COLLISIONS_COLSOLIDWOOD,   SND_GENRL_COLLISIONS_COLSOLIDWOOD,   0,  50  }, // [93]  = SURFACE_P_711SHELF3
    { SND_GENRL_COLLISIONS_COLSOLIDWOOD,   SND_GENRL_COLLISIONS_COLSOLIDWOOD,   0,  50  }, // [94]  = SURFACE_P_RESTUARANTTABLE
    { SND_GENRL_COLLISIONS_COLSOLIDWOOD,   SND_GENRL_COLLISIONS_COLSOLIDWOOD,   0,  50  }, // [95]  = SURFACE_P_BARTABLE
    { -1,                                  -1,                                  0,  20  }, // [96]  = SURFACE_P_UNDERWATERLUSH
    { -1,                                  -1,                                  0,  20  }, // [97]  = SURFACE_P_UNDERWATERBARREN
    { -1,                                  -1,                                  0,  20  }, // [98]  = SURFACE_P_UNDERWATERCORAL
    { -1,                                  -1,                                  0,  20  }, // [99]  = SURFACE_P_UNDERWATERDEEP
    { -1,                                  -1,                                  0,  20  }, // [100] = SURFACE_P_RIVERBED
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [101] = SURFACE_P_RUBBLE
    { SND_GENRL_COLLISIONS_COLSOLIDWOOD,   SND_GENRL_COLLISIONS_COLSOLIDWOOD,   0,  50  }, // [102] = SURFACE_P_BEDROOMFLOOR
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [103] = SURFACE_P_KIRCHENFLOOR
    { SND_GENRL_COLLISIONS_COLSOLIDWOOD,   SND_GENRL_COLLISIONS_COLSOLIDWOOD,   0,  50  }, // [104] = SURFACE_P_LIVINGRMFLOOR
    { SND_GENRL_COLLISIONS_COLSOLIDWOOD,   SND_GENRL_COLLISIONS_COLSOLIDWOOD,   0,  50  }, // [105] = SURFACE_P_CORRIDORFLOOR
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [106] = SURFACE_P_711FLOOR
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [107] = SURFACE_P_FASTFOODFLOOR
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [108] = SURFACE_P_SKANKYFLOOR
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [109] = SURFACE_P_MOUNTAIN
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [110] = SURFACE_P_MARSH
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [111] = SURFACE_P_BUSHY
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [112] = SURFACE_P_BUSHYMIX
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [113] = SURFACE_P_BUSHYDRY
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [114] = SURFACE_P_BUSHYMID
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [115] = SURFACE_P_GRASSWEEFLOWERS
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [116] = SURFACE_P_GRASSDRYTALL
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [117] = SURFACE_P_GRASSLUSHTALL
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [118] = SURFACE_P_GRASSGRNMIX
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [119] = SURFACE_P_GRASSBRNMIX
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [120] = SURFACE_P_GRASSLOW
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [121] = SURFACE_P_GRASSROCKY
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [122] = SURFACE_P_GRASSSMALLTREES
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [123] = SURFACE_P_DIRTROCKY
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [124] = SURFACE_P_DIRTWEEDS
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [125] = SURFACE_P_GRASSWEEDS
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [126] = SURFACE_P_RIVEREDGE
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [127] = SURFACE_P_POOLSIDE
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [128] = SURFACE_P_FORESTSTUMPS
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [129] = SURFACE_P_FORESTSTICKS
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [130] = SURFACE_P_FORRESTLEAVES
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [131] = SURFACE_P_DESERTROCKS
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [132] = SURFACE_P_FORRESTDRY
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [133] = SURFACE_P_SPARSEFLOWERS
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [134] = SURFACE_P_BUILDINGSITE
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [135] = SURFACE_P_DOCKLANDS
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [136] = SURFACE_P_INDUSTRIAL
    { SND_GENRL_COLLISIONS_COLSOLIDWOOD,   SND_GENRL_COLLISIONS_COLSOLIDWOOD,   0,  50  }, // [137] = SURFACE_P_INDUSTJETTY
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [138] = SURFACE_P_CONCRETELITTER
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [139] = SURFACE_P_ALLEYRUBISH
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [140] = SURFACE_P_JUNKYARDPILES
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [141] = SURFACE_P_JUNKYARDGRND
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [142] = SURFACE_P_DUMP
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [143] = SURFACE_P_CACTUSDENSE
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [144] = SURFACE_P_AIRPORTGRND
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [145] = SURFACE_P_CORNFIELD
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [146] = SURFACE_P_GRASSLIGHT
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [147] = SURFACE_P_GRASSLIGHTER
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [148] = SURFACE_P_GRASSLIGHTER2
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [149] = SURFACE_P_GRASSMID1
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [150] = SURFACE_P_GRASSMID2
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [151] = SURFACE_P_GRASSDARK
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [152] = SURFACE_P_GRASSDARK2
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [153] = SURFACE_P_GRASSDIRTMIX
    { -1,                                  -1,                                  0,  20  }, // [154] = SURFACE_P_RIVERBEDSTONE
    { -1,                                  -1,                                  0,  20  }, // [155] = SURFACE_P_RIVERBEDSHALLOW
    { -1,                                  -1,                                  0,  20  }, // [156] = SURFACE_P_RIVERBEDWEEDS
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [157] = SURFACE_P_SEAWEED
    { SND_GENRL_COLLISIONS_COLSOLIDWOOD,   SND_GENRL_COLLISIONS_COLSOLIDWOOD,   0,  70  }, // [158] = SURFACE_DOOR
    { SND_GENRL_COLLISIONS_BARREL_CONE,    SND_GENRL_COLLISIONS_BARREL_CONE,    60, 30  }, // [159] = SURFACE_PLASTICBARRIER
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [160] = SURFACE_PARKGRASS
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [161] = SURFACE_STAIRSSTONE
    { SND_GENRL_COLLISIONS_SOLID_METAL,    SND_GENRL_COLLISIONS_SOLID_METAL,    60, 100 }, // [162] = SURFACE_STAIRSMETAL
    { SND_GENRL_COLLISIONS_COLGRASS,       SND_GENRL_COLLISIONS_COLGRASS,       0,  20  }, // [163] = SURFACE_STAIRSCARPET
    { SND_GENRL_COLLISIONS_SOLID_METAL,    SND_GENRL_COLLISIONS_SOLID_METAL,    60, 100 }, // [164] = SURFACE_FLOORMETAL
    { SND_GENRL_COLLISIONS_CONCRETE,       SND_GENRL_COLLISIONS_CONCRETE,       70, 100 }, // [165] = SURFACE_FLOORCONCRETE
    { SND_GENRL_COLLISIONS_BIN_BAG,        SND_GENRL_COLLISIONS_BIN_BAG,        40, 10  }, // [166] = SURFACE_BIN_BAG
    { SND_GENRL_COLLISIONS_SIGN_A,         SND_GENRL_COLLISIONS_SIGN_B,         50, 80  }, // [167] = SURFACE_THIN_METAL_SHEET
    { SND_GENRL_COLLISIONS_METAL_BARREL,   SND_GENRL_COLLISIONS_METAL_BARREL,   60, 80  }, // [168] = SURFACE_METAL_BARREL
    { SND_GENRL_COLLISIONS_ROADCONE,       SND_GENRL_COLLISIONS_ROADCONE,       30, 20  }, // [169] = SURFACE_PLASTIC_CONE
    { SND_GENRL_COLLISIONS_BARREL_CONE,    SND_GENRL_COLLISIONS_BARREL_CONE,    60, 30  }, // [170] = SURFACE_PLASTIC_DUMPSTER
    { SND_GENRL_COLLISIONS_DUMPSTER,       SND_GENRL_COLLISIONS_DUMPSTER,       50, 80  }, // [171] = SURFACE_METAL_DUMPSTER
    { SND_GENRL_COLLISIONS_FENCE_THIN,     SND_GENRL_COLLISIONS_FENCE_THIN,     70, 40  }, // [172] = SURFACE_WOOD_PICKET_FENCE
    { SND_GENRL_COLLISIONS_FENCE_HEAVY,    SND_GENRL_COLLISIONS_FENCE_HEAVY,    70, 50  }, // [173] = SURFACE_WOOD_SLATTED_FENCE
    { SND_GENRL_COLLISIONS_FENCE_HEAVY,    SND_GENRL_COLLISIONS_FENCE_HEAVY,    70, 50  }, // [174] = SURFACE_WOOD_RANCH_FENCE
    { SND_GENRL_COLLISIONS_HARD_GLASS,     SND_GENRL_COLLISIONS_HARD_GLASS,     30, 50  }, // [175] = SURFACE_UNBREAKABLE_GLASS
    { SND_GENRL_COLLISIONS_HAY_BALE,       SND_GENRL_COLLISIONS_HAY_BALE,       50, 20  }, // [176] = SURFACE_HAY_BALE
    { SND_GENRL_COLLISIONS_GORE_SPLAT1,    SND_GENRL_COLLISIONS_GORE_SPLAT3,    30, 20  }, // [177] = SURFACE_GORE
    { SND_GENRL_COLLISIONS_SOLID_METAL,    SND_GENRL_COLLISIONS_SOLID_METAL,    60, 100 }, // [178] = SURFACE_RAILTRACK

    { -1,                                  -1,                                  0,  0   }, // [179]
    { -1,                                  -1,                                  0,  0   }, // [180]
    { -1,                                  -1,                                  0,  0   }, // [181]
    { -1,                                  -1,                                  0,  0   }, // [182]
    { -1,                                  -1,                                  0,  0   }, // [183]
    { -1,                                  -1,                                  0,  0   }, // [184]
    { -1,                                  -1,                                  0,  0   }, // [185]
    { -1,                                  -1,                                  0,  0   }, // [186]
    { -1,                                  -1,                                  0,  0   }, // [187]

    { SND_GENRL_COLLISIONS_BIKE_CRASH1,    SND_GENRL_COLLISIONS_BIKE_CRASH5,    90, 60  }, // [188] = AE_SURFACE_TYPE_BMX            
    { SND_GENRL_COLLISIONS_BOTTLE_SMASH,   SND_GENRL_COLLISIONS_BOTTLE_SMASH,   0,  30  }, // [189] = AE_SURFACE_TYPE_MOLOTOV        
    { SND_GENRL_COLLISIONS_SATCHEL_CHARGE, SND_GENRL_COLLISIONS_SATCHEL_CHARGE, 0,  40  }, // [190] = AE_SURFACE_TYPE_SATCHEL_CHARGE 
    { SND_GENRL_COLLISIONS_GRENADE,        SND_GENRL_COLLISIONS_GRENADE,        0,  30  }, // [191] = AE_SURFACE_TYPE_GRENADE        
    { SND_GENRL_COLLISIONS_GRASS_SKID,     SND_GENRL_COLLISIONS_METAL_SCRAPE,   0,  70  }, // [192] = AE_SURFACE_TYPE_POOL_BALL      
    { SND_GENRL_COLLISIONS_GRASS_SKID,     SND_GENRL_COLLISIONS_METAL_SCRAPE,   0,  30  }, // [193] = AE_SURFACE_TYPE_BASKETBALL     
    { SND_GENRL_COLLISIONS_BARREL_CONE,    SND_GENRL_COLLISIONS_BIKE_CRASH2,    0,  40  }  // [194] = AE_SURFACE_TYPE_PUNCHBAG       
}};
